.github/workflows/lint.yml, .github/workflows/test.yml, CMakeLists.txt, CONTRIBUTING.md, LICENSE, README.md, include/libstatistics_collector/collector/collector.hpp, include/libstatistics_collector/collector/generate_statistics_message.hpp, include/libstatistics_collector/collector/metric_details_interface.hpp, include/libstatistics_collector/moving_average_statistics/moving_average.hpp, include/libstatistics_collector/moving_average_statistics/types.hpp, include/libstatistics_collector/topic_statistics_collector/constants.hpp, include/libstatistics_collector/topic_statistics_collector/received_message_age.hpp, include/libstatistics_collector/topic_statistics_collector/received_message_period.hpp, include/libstatistics_collector/topic_statistics_collector/topic_statistics_collector.hpp, package.xml, src/libstatistics_collector/collector/collector.cpp, src/libstatistics_collector/collector/generate_statistics_message.cpp, src/libstatistics_collector/moving_average_statistics/moving_average.cpp, src/libstatistics_collector/moving_average_statistics/types.cpp, test/collector/test_collector.cpp, test/moving_average_statistics/test_moving_average_statistics.cpp, test/msg/DummyMessage.msg, test/topic_statistics_collector/test_received_message_age.cpp, test/topic_statistics_collector/test_received_message_period.cpp
Related to: https://github.com/ros-tooling/aws-roadmap/issues/248
Note: this is just a move and CI has not been added yet, because CI depends on https://github.com/ros-tooling/metrics_statistics_msgs/pull/1. CI will be added in another PR.
=> Moved libstatistics_collector folder from system_metrics_collector

LICENSE
Signed-off-by: Emerson Knapp <emerson.b.knapp@gmail.com>
=> Fix license format

README.md
=> Fix README test badge

src/libstatistics_collector/collector/generate_statistics_message.cpp
=> Fix windows warning

CMakeLists.txt
=> export targets in a addition to include directories / libraries

.github/workflows/test.yml
=> Bump setup-ros to 0.0.20

.github/workflows/lint.yml, .github/workflows/test.yml
=> Bump actions versions

Doxyfile
Added Doxyfile to include this package as part of the ROS 2 public API, available at docs.ros2.org. 
=> Added Doxyfile

.github/workflows/test.yml, CONTRIBUTING.md, QUALITY_DECLARATION.md, README.md
=> Added quality declaration

Doxyfile, include/libstatistics_collector/collector/collector.hpp, include/libstatistics_collector/moving_average_statistics/types.hpp, include/libstatistics_collector/topic_statistics_collector/received_message_age.hpp, include/libstatistics_collector/topic_statistics_collector/received_message_period.hpp, include/libstatistics_collector/topic_statistics_collector/topic_statistics_collector.hpp
=> Removed doxygen warnings

.github/workflows/test.yml
=> Don't attempt to report if originating from a fork

QUALITY_DECLARATION.md
=> Updated QD Performance tests

QUALITY_DECLARATION.md, README.md
It depends on this PR in RCL https://github.com/ros2/rcl/pull/858
@chapulina
=> Updated QD

.github/workflows/lint.yml, .github/workflows/test.yml
=> Bump action-ros-ci to 0.1.0

QUALITY_DECLARATION.md, README.md
=> [foxy-devel] Update QD to QL 1

include/libstatistics_collector/topic_statistics_collector/received_message_age.hpp, include/libstatistics_collector/topic_statistics_collector/received_message_period.hpp
Closes #79
Signed-off-by: hsgwa <hasegawa@isp.co.jp>
=> fix: measured values after the decimal point are truncated #79

.github/workflows/test.yml
=> Remove cloudwatch reporting

CHANGELOG.rst, package.xml
Update the changelog and bump the minor version.
=> Prepare for 1.5.0

CHANGELOG.rst, package.xml
=> Foxy patch release 1.0.2

include/libstatistics_collector/topic_statistics_collector/received_message_age.hpp, include/libstatistics_collector/topic_statistics_collector/received_message_period.hpp, include/libstatistics_collector/topic_statistics_collector/topic_statistics_collector.hpp
These fixes should also be backwards compatible with the old version of uncrustify.
=> Fixes for newer uncrustify.

CHANGELOG.rst
Once this is approved, I'll go ahead and merge it in and then do the 1.7.1 release.
=> Changelog for 1.7.1
